[general]
import = ["/home/dario/.gruvbox_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 1000

[cursor.style]
blinking = "Always"

[font]
size = 20.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\r"
key = "NumpadEnter"

[window]
decorations = "Full"
dynamic_title = true
opacity = 1
startup_mode = "Fullscreen"
title = ""

[window.padding]
x = 2
y = 2
