[tools]
uv = "latest"
node = "latest"
go = "latest"
operator-sdk = "latest"
ripgrep = "latest"
websocat = "latest"
maven = "3.9.4"
python = "latest"
jq = "latest"
kubectl = "latest"
krew = "latest"
neovim = "latest"
kustomize = "latest"
packer = "latest"
cilium-cli = "latest"
yq = "latest"
eza = "latest"
helm = "latest"
usage = "latest"
kubens = "latest"
kubectx = "latest"
zoxide = "latest"
atuin = "18.20.1"
tmux = "latest"
opentofu = "latest"
bat = "latest"
java = "21"
stern = "latest"
argocd = "latest"
zig = "latest"
ollama = "latest"
golangci-lint = "latest"
goreleaser = "latest"
rust = "latest"
yt-dlp = "latest"
shellcheck = "latest"
gh-cli = "latest"
longhorn-cli = "latest"
kind = "latest"
ginko = "latest"
gsa = "latest"
xq = "latest"
goda = "latest"
huggingface-hub-cli = "latest"

[tool_alias]
zoxide = "aqua:ajeetdsouza/zoxide"
kubectx = "github:ahmetb/kubectx"
kubens = "github:ahmetb/kubectx"
kustomize = "aqua:kubernetes-sigs/kustomize"
operator-sdk = "aqua:operator-framework/operator-sdk"
ripgrep = "aqua:BurntSushi/ripgrep"
websocat = "aqua:vi/websocat"
maven = "aqua:apache/maven"
jq = "aqua:jqlang/jq"
kubectl = "aqua:kubernetes/kubernetes/kubectl"
krew = "aqua:kubernetes-sigs/krew"
neovim = "aqua:neovim/neovim"
packer = "aqua:hashicorp/packer"
cilium-cli = "aqua:cilium/cilium-cli"
opentofu = "aqua:opentofu/opentofu"
bat = "aqua:sharkdp/bat"
yt-dlp = "github:yt-dlp/yt-dlp"
shellcheck = "aqua:koalaman/shellcheck"
gh-cli = "github:cli/cli"
longhorn-cli = "github:longhorn/cli"
kind = "aqua:kubernetes-sigs/kind"
ginko = "go:github.com/onsi/ginkgo/v2/ginkgo"
gsa = "go:github.com/Zxilly/go-size-analyzer/cmd/gsa"
xq = "go:github.com/sibprogrammer/xq"
goda = "go:github.com/loov/goda"
huggingface-hub-cli = "pipx:huggingface_hub[cli]"

[settings]
trusted_config_paths = [
  '$ENV{HOME}/./config/mise/config.toml',
]
experimental = true
