[tools]
node = 'latest'
go = 'latest'
operator-sdk = "latest"
ripgrep = "latest"
websocat = "latest"
java = "17"
maven = '3.9.4'
python = "latest"
youtube-dl = "latest"
linkerd = "latest"
jq = "latest"
kubectl = "latest"
krew = "latest"
neovim = "latest"
kustomize = "latest"

[settings]
trusted_config_paths = [
  '$ENV{HOME}/./config/rtx/config.toml',
]
