[tools]
node = 'latest'
go = '1.21.1'
operator-sdk = "1.31.0"
ripgrep = "latest"
websocat = "latest"
java = '21.0.0'
maven = '3.9.4'
python = "latest"
youtube-dl = "latest"
linkerd = "latest"
jq = "latest"
kubectl = "latest"
krew = "latest"
neovim = "latest"

[settings]
trusted_config_paths = [
  '$ENV{HOME}/./config/rtx/config.toml',
]
