[tools]
node = "latest"
go = "latest"
operator-sdk = "latest"
ripgrep = "latest"
websocat = "latest"
java = "17"
maven = "3.9.4"
python = "latest"
youtube-dl = "latest"
linkerd = "latest"
jq = "latest"
kubectl = "latest"
krew = "latest"
neovim = "latest"
kustomize = "latest"
packer = "1.9.4"
cilium-cli = "latest"
cilium-hubble = "latest"

[plugins]
cilium-cli = "https://github.com/carnei-ro/asdf-cilium-cli.git" 
cilium-hubble = "https://github.com/NitriKx/asdf-cilium-hubble.git"

[settings]
trusted_config_paths = [
  '$ENV{HOME}/./config/rtx/config.toml',
]
